### PR TITLE
Port from pyb to machine

### PR DESCRIPTION
**Pull request by maxlock**
First attempt at porting from pyb to machine so it can be used on the esp8266. Probably awful and gives me some suspicious values. :)

```
>>> from bmp180 import BMP180
>>> bmp180 = BMP180()
pass either X or Y, defaulting to Y
>>> bmp180.oversample_sett = 2
>>> bmp180.baseline = 101325
>>> temp = bmp180.temperature
>>> p = bmp180.pressure
>>> altitude = bmp180.altitude
>>> print(temp, p, altitude)
29.05247 102064.7 -58.45096
```

### CODE REVIEW

**Comment by turbinenreiter** [comment]
Looks fine to me.
Which values do you consider suspicious?

**Comment by maxlock** [comment]
Oh the temp value is probably 10 degrees high. Plus I was concerned about using time.sleep_ms instead of the original loops in case they blocked too much.

**Comment by turbinenreiter** [comment]
There is no error in the code that could lead to a higher-than-real temperature, so I guess there is something else happening. I also usually see temperatures higher than expected.

It's true that using `time.sleep_ms()` is blocking, rendering the whole generator useless. However, the fix for that is trivial:
`pyb.millis()` is the same as `time.ticks_ms`
`pyb.elapsed_millis(t_start)` is the same as `time.ticks_ms - t_start`

If you make these changes, I can merge, if you don't I can apply them myself.

Thanks for your work! It's nice when people actually sit down to do the pull requests.

**Comment by maxlock** [comment]
There you go, I've tested and pushed a new commit, much faster. Temperatures still way off though ;)

**Pull request merged**
